version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mot2P@ss
      POSTGRES_DB: edjo_auth_db
    volumes:
      - C:\Users\ola\Documents\docker-data\postgres-volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: mot2P@ss
    volumes:
      - C:\Users\ola\Documents\docker-data\pg-admin-volume:/var/lib/pgadmin